name = "my-worker"
account_id = "your-account-id"  # 替换为你的Cloudflare Account ID
main = "src/index.js"
compatibility_date = "2025-10-23"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[vars]
user = "0acb0ed8-9c48-4048-b8d5-5c336bb76842"
target = "bpb.yousef.isegaro.com"
