name = "my-worker"
account_id = "76abf68faef4a57f43947ab980872d68"  # 替换为你的Cloudflare Account ID
main = "src/index.js"
compatibility_date = "2025-10-22"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[vars]
user = "0acb0ed8-9c48-4048-b8d5-5c336bb76842"
target = "203.0.113.5"
